# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-05 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarvelDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('url_slug', models.CharField(max_length=200)),
                ('identity_status', models.CharField(max_length=200)),
                ('align', models.CharField(max_length=200)),
                ('eye_color', models.CharField(max_length=200)),
                ('hair_color', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('gsm', models.CharField(max_length=200)),
                ('alive', models.CharField(max_length=200)),
                ('appearances', models.CharField(max_length=200)),
                ('first_appearance', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
            ],
        ),
    ]
