# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marveldatabase',
            name='is_well_known',
            field=models.BooleanField(default=False),
        ),
    ]
